// <auto-generated />
namespace DVDRentalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dvddetailsloanstatus4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dvddetailsloanstatus4));
        
        string IMigrationMetadata.Id
        {
            get { return "202005151228416_dvddetailsloanstatus4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
